analytics: {}
color:
  brandColors:
    - '#000000'
    - '#857500'
    - '#000000'
    - '#C8B000'
    - '#88A0C8'
  brandStrength: 0.295608
  lightness: 0.739765
  rhythmicContrast: 0.552039
  saturation: 0.717369
cta: {}
layout_spectrum: 0.658784
name: geniecanvas
opengraph: {}
purpose: []
typography_spectrum: 0.622466
